### ISSUE TITLE
Issues with boundary conditions in diffusion1

### ISSUE THREAD

**Issue by KennethJAllen** [project-asgard/DG-SparseGrid#25]
I'm IIF branch, running mydiffusiontest.m which uses diffusion1. The default analytic solution to the diffusion PDE on the reference branch is `exp(-2*pi^2*t)*cos(x)` on the interval [0,1]. Letting `dt = 3.9063e-05`, and end time `T=0.3`, (I don't quite remember the level and degree), `mydiffusiontest.m` gives the following results for the Krylov IIF, forward Euler, and backwards Euler methods:
![stability2](https://user-images.githubusercontent.com/54598311/80895374-27526500-8cb2-11ea-9086-7589ca6689ce.jpg)

The solution is fixed on the right, but not the left.

I changed diffusion1 so that the solution is homogeneous with analytic solution `exp(-2*t)*sin(x)` on the interval [0,pi]. Letting `dt = 5.3e-04` and `T=0.1`, level = 4, and degree = 3, `mydiffusiontest.m` gives the following result for the Krylov IIF and forward Euler method:

![diffEq](https://user-images.githubusercontent.com/54598311/80895745-4226d880-8cb6-11ea-87f8-d8e0fea597c1.jpg)

Once again, the oscillation is happening on the left boundary.

**Comment by MollyRaver** [comment]
For the second figure, does dt = 5.3e-04 satisfy the forward Euler's time-stepping constrain? Please make sure it is instability or non-matching of bc. 

Looks like it is due to the flux choice as right flux. The right boundary is enforced but the left boundary is not. Please make sure the diffusion equation is employed with the correct flux condition.

**Comment by lwonnell** [comment]
It looks like Forward Euler cannot handle dt = 5e-04. When you have a low time-step the choice of flux will determine which boundary condition oscillates for the FE. The best combination, I have found, is pterm2 using downwind (-1) and pterm1 using upwind (+1), but the main problem with FE is the choice of time step.

**Comment by KennethJAllen** [comment]
Okay thank you both, it does seem due to the choice of flux. For the second case, yes dt = 5e-04 is too large of a time step. I was mostly confused as to why it broke specifically on the left, but again it seems choice of flux influences which side breaks first.
